import React from 'react';
import "./Documents.css";

function Documents() {
    return (
        <div className="documents">
            <div className="sub_documents">
            <div className="main_docs">
                <h2>Our Services</h2>
                    <p>For both our domestic and international clients, Our Company offers a multi-tiered platform for growth:</p>
                    <p><strong>PROSPECTUS WRITING:</strong>  Our team writes prospectus for both private and public offering.  We develop prospectus and red herring offerings, as well as offering circulars for virtually all major stock exchanges worldwide, for debt and equity listing.  In addition, we also file all needed paperwork with the proper regulatory and government agencies in any given country.</p>
                    <p><strong>INITIAL PUBLIC OFFERING (IPO) SERVICES:</strong>  Our Company assists global companies with listing via Initial Public Offerings (IPO’s) for the world’s most popular stock exchanges.  Whether you are seeking a listing on the London Stock exchange or in Frankfurt, or in the U.S. with Nasdaq or the New York Stock Exchange, all the way over to the Hong Kong Stock Exchange, our team can help.</p>
                    <p><strong>FUND SETUP:</strong>  Our Company is a world leader in the formation of onshore and offshore funds.  Our staff provides many services for fund structuring, growth and sustainability.  We can provide ongoing hedge fund or mutual fund consultation and assist with all administrative tasks.  Our team assists in structuring the fund from the very onset, from the type of fund, the domicile (fund location) and overall goal of investment.  Aside from fund setup and compliance, we can also assist with marketing and the introduction of your fund to broker dealers or investors who may assist with your offering.</p>
                    <p><strong>HEDGE FUNDS & MUTUAL FUNDS:</strong>  Our Company’s team can draft your hedge fund prospectus for virtually any jurisdiction worldwide.  We are the most efficient, cost effective and proficient firm in the industry.  Our team can prepare and assist in the filing of all paperwork with regulators and help to launch the fund.  Our industry leading firm specializes in hedge fund setup and document drafting for nearly all paperwork, including the prospectus, the offering memorandum and the private placement memorandum.  We develop the hedge fund prospectus for various onshore and offshore jurisdictions and for numerous hedge fund offerings for limited partnerships (LP or LLP), LLCs (limited liability companies), open ended and closed ended funds, UCITS,  umbrella structure and more.</p>
                    <p><strong>REGISTRATION AND FILING:</strong> The Our Company legal team assists clients with the registration and filing of their legal work with various compliance agencies and government bodies.  Aside from drafting the prospectus, we will also file statements such as the S-1 and other compliance documentation.  We prepare full investment disclosure documents, such as the offering circular, and cover the full spectrum of both public and private placement offerings and their respective filings (such as filing the Form D for Reg D offerings for private placements and the S-1, for example, for public offerings).  Further, our team at Prospectus is always happy to leverage our extensive industry knowledge and contacts with broker dealers, investment advisors, underwriters, investment banks, hedge funds and PIPE funds to identify possible strategic partners who can help our clients grow their businesses in an efficient, time-saving, low-cost manner.</p>
                    <p><strong>LEGAL WORK:</strong> Our Company securities attorneys and documentation experts are industry agnostic.  We have worked with issuers across all major industries and are fluent in the nuances of respective industry regulations that Issuers may be subject to.  From traditional offerings, to REITs to energy industry Master Limited Partnerships (MLPs), our consultants utilize our proprietary library of documentation, comprised of thousands of Issues that have been successfully placed with institutional investors and qualified high net worth investors domiciled in virtually every part of the world.  If you need anything written or edited by securities or general business attorneys just let us know.  Our team consists of securities specialists, general business advisors and others such as patent and trademark advisors.  Our Company can help create all major corporate entities, including LLC’s, LP’s, S and C Corporations, as well as write a company’s by-laws, operating or limited partnership agreements.</p>
                    <p><strong>BUSINESS PLANS:</strong>  Our firm offers a variety of business plans tailored to the needs of the client’s business model.  Through Our Company’s proprietary business planning and consultation methodology, we develop business plans that are first and foremost geared toward raising capital.  All of our business plans are investor, bank, and/or SBA compatible and are designed to develop and grow their businesses.</p>
                    <p><strong>FEASIBILITY STUDY:</strong>  Our team is a world class leader in preparing and writing feasibility study reports.  Our staff of researchers, business plan and financial consultants and attorneys have written hundreds of feasibility study documents in more than 50 countries.  We have written feasibility studies for a diverse range of industries and businesses, including real estate development, oil, gas and energy, product launching, scientific exploration and much more.
                    </p>
                </div>
            </div>
        </div>
    )
}

export default Documents;
